version: '3'
services: 
    app:
        container_name: pmo-nest-mongo
        restart: always
        build: .
        ports: 
            - '80:4000'
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'