version: '3'
services: 
    app:
        container_name: pmo-nest
        restart: always
        build: .
        environment:
            - MONGO_URI=${MONGO_URI}
        ports: 
            - '80:4000'
        links: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
